# Generated by Django 3.0.2 on 2020-05-01 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guild', '0002_readingevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingevent',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='readingevent',
            name='date of the event',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingevent',
            name='date published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='readingevent',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingevent',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='readingevent',
            name='event_text',
            field=models.TextField(),
        ),
    ]
