# Generated by Django 3.0.2 on 2020-05-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_auto_20200501_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingevent',
            old_name='date published',
            new_name='date created',
        ),
    ]
