# Generated by Django 3.0.2 on 2020-05-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_auto_20200502_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingevent',
            old_name='date created',
            new_name='created_date',
        ),
    ]
